"""emergence fix

Revision ID: c21af6c3d154
Revises: 26b8c9d162ea
Create Date: 2025-07-22 00:56:02.676445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c21af6c3d154'
down_revision = '26b8c9d162ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.drop_column('update_at')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('image_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['sqe'])
        batch_op.drop_column('update_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('image_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
